Lambda-School-Labs/didact-be

- auth/facebookAuth.js
- database/migrations/20191009164112_bootstrap.js
- users/usersModel.js
> userModel, migrations updated

- auth/facebookAuth.js
> fixing elis errors

- auth/facebookAuth.js
> eli made a big mistake

- auth/facebookAuth.js
> sends picture back

- auth/facebookAuth.js
> logging profile

- auth/facebookAuth.js
> fixing requets timeout

- auth/facebookAuth.js
> adding done so it goes to callback function

- auth/facebookAuth.js
> Sends nicer object back

- users/usersModel.js
> changing userModel

- users/usersModel.js
> return newUser with id

- api/server.js
- auth/googleAuth.js
- config/secret.js
- package.json
- users/usersModel.js
> Passport auth

- auth/googleAuth.js
> Fixed comment bug

- api/server.js
- auth/authRouter.js
- courses/coursesRouter.js
- courses/udemyCoursesRouter.js
- utils/checkCourseLink.js
Udemy API work started.
Also, verify token on BE now returns user id
> udemy api partial, verify token returns user id

- auth/authRouter.js
> changes to grab photo

- learning-paths/learningPathsRouter.js
> logs to figure what's going on

- docs/api_data.js
- docs/api_data.json
- docs/api_project.js
- docs/api_project.json
- learning-paths/learningPathsRouter.js
> added get your learning path order

- docs/api_data.js
- docs/api_data.json
- docs/api_project.js
- docs/api_project.json
- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
Replaced update course order with update content order. Maybe this works. Will need to remove some other stuff for update path item order as well.
> content order updated, maybe?

- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
> get learning paths now returns the ones the user hasn't joined

- learning-paths/learningPathsModel.js
> moved whereNot up a line

- learning-paths/learningPathsModel.js
> filter fix, maybe

- database/migrations/20191009164112_bootstrap.js
- learning-paths/learningPathsModel.js
> bug fixing

- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
> updated for get owned LP

- courses/coursesModel.js
- learning-paths/learningPathsModel.js
> some bug fixes, nothing udemy related

- courses/coursesModel.js
> Jon didn't help at all

- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
> return completion for get your paths

- learning-paths/learningPathsModel.js
Co-authored-by: Seth Nadu <47128498+sethnadu@users.noreply.github.com>
> added field to get yourpaths

- database/seeds/02-courses.js
- database/seeds/13-users_courses.js
- database/seeds/14-users_sections.js
- database/seeds/15-users_section_details.js
- database/seeds/16-users_section_details_2.js
> seed data added

- database/seeds/12-users_path_items.js
- database/seeds/13-users_courses.js
> Mark complete

- database/seeds/01-users.js
- knexfile.js
made changes to incorporate postgres local database.
> made changes to incorporate postgres local database

- auth/authRouter.js
- courses/coursesModel.js
- courses/coursesRouter.js
- knexfile.js
- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
> Model router conditionals

- courses/coursesModel.js
- learning-paths/learningPathsModel.js
> fixed array flattening in models

- README.md
- auth/authRouter.js
- courses/coursesModel.js
- courses/coursesRouter.js
- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
> Testing crud

- api/server.js
- courses/coursesRouter.js
- database/migrations/20191009164112_bootstrap.js
- database/seeds/03-paths.js
- database/seeds/04-external_articles.js
- database/seeds/09-tags_external_articles.js
- resources/articlesModel.js
- resources/articlesRouter.js
- resources/sourcesModel.js
- resources/sourcesRouter.js
- resources/toolsModel.js
- resources/toolsRouter.js
- users/usersModel.js
> Resource endpoints

- courses/coursesRouter.js
- database/migrations/20191009164112_bootstrap.js
- database/seeds/04-articles.js
- database/seeds/04-external_articles.js
- database/seeds/06-tools.js
- database/seeds/09-tags_paths.js
- learning-paths/learningPathsModel.js
- resources/articlesModel.js
- resources/articlesRouter.js
> External article

- courses/coursesRouter.js
Correcting bug with correct code from Kodi's source file in courseRouter.
> Corrected data in courseRouter

- auth/authRouter.js
- auth/facebookAuth.js
- auth/googleAuth.js
- courses/coursesModel.js
- courses/coursesRouter.js
- courses/udemyCoursesRouter.js
- learning-paths/learningPath.spec.js
- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
- users/usersModel.js
> Learning paths tests

- database/migrations/20191009164112_bootstrap.js
- users/usersModel.js
> updated tables with team

- auth/authRouter.js
- users/usersModel.js
> fixed post user profile route

- users/usersModel.js
> fixed post user profile route and model

- auth/authRouter.js
- database/seeds/01.5-user_profile.js
- users/usersModel.js
> new user profile seeds added, working on modifying register

- auth/authRouter.js
- users/usersModel.js
> register now posts an initial user profile working well

- api/server.js
- auth/authRouter.js
- database/migrations/20191009164112_bootstrap.js
- uploads/multer.js
- users/usersModel.js
- utils/middleware.js
> Image integration

- PROJECTNOTES.md
- README.md
- discord/didactBot.js
- learning-paths/learningPathsModel.js
- learning-paths/learningPathsRouter.js
- package.json
> Discord bot connect

- PROJECTNOTES.md
> project notes updated
